---
- name: Definir senha do usuário no Cognito
  hosts: localhost  
  tasks:
    - name: Executar comando AWS Cognito
      command: >
        aws cognito-idp admin-set-user-password
        --user-pool-id us-east-1_n0saO3hxS
        --username {{phone}}
        --password Musa1234
        --permanent
      environment:
        WS_ACCESS_KEY_ID: "{{ lookup('env','AWS_ACCESS_KEY_ID') }}"
        AWS_SECRET_ACCESS_KEY: "{{ lookup('env','AWS_SECRET_ACCESS_KEY') }}"
      become: no  
